// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDMWUpytaEHpykTDDXsCNYTIjTD5-4h0AA",
    authDomain: "myfristproject-dd7da.firebaseapp.com",
    projectId: "myfristproject-dd7da",
    storageBucket: "myfristproject-dd7da.firebasestorage.app",
    messagingSenderId: "1043234910102",
    appId: "1:1043234910102:web:8bce53cba2080fe048f7b7",
    measurementId: "G-2Y1JNER5TK",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWUpytaEHpykTDDXsCNYTIjTD5-4h0AA',
    appId: '1:1043234910102:web:8bce53cba2080fe048f7b7',
    messagingSenderId: '1043234910102',
    projectId: 'myfristproject-dd7da',
    storageBucket: 'myfristproject-dd7da.firebasestorage.app',
  );
}
